### ISSUE TITLE
The New Website (Checklist)

### ISSUE THREAD

**Issue by rasmusolle** [Text-OS/Text-OS.github.io#1]
- [x] Main CSS work (Done by template)
- [x] Homepage page
- [x] About page
- [x] Blog page
- [x] Why Text-OS? page
- [x] Download page
- [x] Changelog page
- [x] Work on the footer

**Comment by rasmusolle** [comment]
We're so close to completion!

**Comment by rasmusolle** [comment]
These things r done
